export const FETCH_STAR_WARS_REQUEST = 'FETCH_STAR_WARS_REQUEST'
export const FETCH_STAR_WARS_SUCCESS = 'FETCH_STAR_WARS_SUCCESS'
export const FETCH_STAR_WARS_PLANET_REQUEST = 'FETCH_STAR_WARS_PLANET_REQUEST'
export const FETCH_STAR_WARS_PLANETS_SUCCESS = 'FETCH_STAR_WARS_PLANETS_SUCCESS'